#!/usr/bin/env python3
"""Render one pattern, or select a supplied example. Never publishes to Confluence."""
import argparse
import json
import sys
from pathlib import Path
from motion import ROOT, render, document
from validate_html_macro import validate


def main() -> int:
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('pattern')
    p.add_argument('output',type=Path)
    source=p.add_mutually_exclusive_group(required=True)
    source.add_argument('--input',type=Path)
    source.add_argument('--example',action='store_true')
    p.add_argument('--prefix',help='Optional unique prefix; generated by default')
    p.add_argument('--preview',type=Path)
    args=p.parse_args()
    try:
        data=json.loads(args.input.read_text(encoding='utf-8')) if args.input else json.loads((ROOT/'examples/motion-inputs.json').read_text(encoding='utf-8'))[args.pattern]
        fragment=render(args.pattern,data,args.prefix)
        errors=validate(fragment)
        if errors:
            raise ValueError('; '.join(errors))
        args.output.parent.mkdir(parents=True,exist_ok=True)
        args.output.write_text(fragment,encoding='utf-8')
        if args.preview:
            args.preview.parent.mkdir(parents=True,exist_ok=True)
            args.preview.write_text(document(fragment),encoding='utf-8')
        print(f'PASS: {args.output}')
        return 0
    except (ValueError,KeyError,OSError) as e:
        print(f'FAIL: {e}',file=sys.stderr)
        return 1

if __name__=='__main__':
    raise SystemExit(main())
